services: 

  db:
    image: postgres
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=1234
    ports: 
      - "5432:5432"
    networks: 
      - node-network

  back-end:
    build: 
      context: back-end
    container_name: back-end
    networks: 
      - node-network
    volumes: 
      - ./back-end:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3001:3001"
    depends_on:
       - db

  front-end:
    build: 
      context: front-end
    container_name: front-end
    networks: 
      - node-network
    volumes: 
      - ./front-end:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3000:3000"
    command: npm start

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - node-network
    depends_on:
      - front-end
      - back-end

networks: 
  node-network:
    driver: bridge