import Plant from "../Classes/Plant";
const mockPlants = [
  {
    "name": "nvdlm",
    "common_name": "Rubber Plant",
    "scientific_name": "Ficus elastica",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-21",
    "watering_frequency_days": 11,
    "soil_type": "Cactus mix",
    "plant_type": "Foliage plant",
    "location": "Bathroom",
    "last_fertilization": "2025-04-20"
  },
  {
    "name": "rowhjlpnqweq",
    "common_name": "Cactus",
    "scientific_name": "Cactaceae family",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-29",
    "watering_frequency_days": 3,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Desert succulent",
    "location": " Downstairs Bedroom",
    "last_fertilization": "2025-04-15"
  },
  {
    "name": "qmrygvzlfkxs",
    "common_name": "Monstera Deliciosa",
    "scientific_name": "Monstera deliciosa",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-26",
    "watering_frequency_days": 11,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Flowering indoor",
    "location": "Living Room",
    "last_fertilization": "2025-04-02"
  },
  {
    "name": "ry",
    "common_name": "Monstera Deliciosa",
    "scientific_name": "Monstera deliciosa",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-21",
    "watering_frequency_days": 13,
    "soil_type": "Cactus mix",
    "plant_type": "Tropical indoor",
    "location": "Bathroom",
    "last_fertilization": "2025-03-19"
  },
  {
    "name": "szwyywhcuxxvo",
    "common_name": "Spider Plant",
    "scientific_name": "Chlorophytum comosum",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-24",
    "watering_frequency_days": 9,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Air-purifying",
    "location": "Upstairs Bedroom",
    "last_fertilization": "2025-03-07"
  },
  {
    "name": "tpuz",
    "common_name": "Philodendron",
    "scientific_name": "Philodendron hederaceum",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-22",
    "watering_frequency_days": 8,
    "soil_type": "Cactus mix",
    "plant_type": "Tropical indoor",
    "location": "Upstairs",
    "last_fertilization": "2025-04-17"
  },
  {
    "name": "elawhrv",
    "common_name": "Aloe Vera",
    "scientific_name": "Aloe barbadensis miller",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-26",
    "watering_frequency_days": 6,
    "soil_type": "Loamy soil",
    "plant_type": "Tropical indoor",
    "location": "Office",
    "last_fertilization": "2025-04-24"
  },
  {
    "name": "vrkboy",
    "common_name": "Peace Lily",
    "scientific_name": "Spathiphyllum wallisii",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-28",
    "watering_frequency_days": 14,
    "soil_type": "Loamy soil",
    "plant_type": "Air-purifying",
    "location": "Bathroom",
    "last_fertilization": "2025-02-28"
  },
  {
    "name": "rolukluxxshyr",
    "common_name": "Fiddle Leaf Fig",
    "scientific_name": "Ficus lyrata",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-15",
    "watering_frequency_days": 10,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Foliage plant",
    "location": "Bathroom",
    "last_fertilization": "2025-03-27"
  },
  {
    "name": "snxwutmqyeh",
    "common_name": "Monstera Deliciosa",
    "scientific_name": "Monstera deliciosa",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-23",
    "watering_frequency_days": 11,
    "soil_type": "Sandy soil",
    "plant_type": "Flowering indoor",
    "location": "Kitchen",
    "last_fertilization": "2025-03-16"
  },
  {
    "name": "adxvovfvzi",
    "common_name": "Bamboo Palm",
    "scientific_name": "Chamaedorea seifrizii",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-29",
    "watering_frequency_days": 11,
    "soil_type": "Sandy soil",
    "plant_type": "Tropical indoor",
    "location": "Office",
    "last_fertilization": "2025-04-03"
  },
  {
    "name": "nrrcrenyyzo",
    "common_name": "Croton",
    "scientific_name": "Codiaeum variegatum",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-19",
    "watering_frequency_days": 13,
    "soil_type": "Cactus mix",
    "plant_type": "Foliage plant",
    "location": "Living Room",
    "last_fertilization": "2025-04-24"
  },
  {
    "name": "vxlrd",
    "common_name": "Peace Lily",
    "scientific_name": "Spathiphyllum wallisii",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-19",
    "watering_frequency_days": 10,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Desert succulent",
    "location": "Living Room",
    "last_fertilization": "2025-04-28"
  },
  {
    "name": "ebfdu",
    "common_name": "Philodendron",
    "scientific_name": "Philodendron hederaceum",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-19",
    "watering_frequency_days": 11,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Tropical indoor",
    "location": "Upstairs Bedroom",
    "last_fertilization": "2025-03-06"
  },
  {
    "name": "hzxbydlua",
    "common_name": "Snake Plant",
    "scientific_name": "Sansevieria trifasciata",
    "description": "Purifies air and adds greenery to your space.",
    "last_water_date": "2025-04-20",
    "watering_frequency_days": 10,
    "soil_type": "Sandy soil",
    "plant_type": "Air-purifying",
    "location": "Office",
    "last_fertilization": "2025-03-14"
  },
  {
    "name": "nbp",
    "common_name": "Spider Plant",
    "scientific_name": "Chlorophytum comosum",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-18",
    "watering_frequency_days": 4,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Tropical indoor",
    "location": "Music Room",
    "last_fertilization": "2025-04-29"
  },
  {
    "name": "f",
    "common_name": "Philodendron",
    "scientific_name": "Philodendron hederaceum",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-21",
    "watering_frequency_days": 7,
    "soil_type": "Cactus mix",
    "plant_type": "Air-purifying",
    "location": "Living Room",
    "last_fertilization": "2025-03-23"
  },
  {
    "name": "nzltlhsvnle",
    "common_name": "Fiddle Leaf Fig",
    "scientific_name": "Ficus lyrata",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-24",
    "watering_frequency_days": 13,
    "soil_type": "Cactus mix",
    "plant_type": "Flowering indoor",
    "location": "Music Room",
    "last_fertilization": "2025-04-16"
  },
  {
    "name": "oeqfarjblesm",
    "common_name": "ZZ Plant",
    "scientific_name": "Zamioculcas zamiifolia",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-17",
    "watering_frequency_days": 11,
    "soil_type": "Sandy soil",
    "plant_type": "Flowering indoor",
    "location": "Upstairs",
    "last_fertilization": "2025-04-19"
  },
  {
    "name": "ujtlgjptriz",
    "common_name": "Aloe Vera",
    "scientific_name": "Aloe barbadensis miller",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-23",
    "watering_frequency_days": 8,
    "soil_type": "Cactus mix",
    "plant_type": "Air-purifying",
    "location": "Upstairs Bedroom",
    "last_fertilization": "2025-03-14"
  },
  {
    "name": "awc",
    "common_name": "Areca Palm",
    "scientific_name": "Dypsis lutescens",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-29",
    "watering_frequency_days": 4,
    "soil_type": "Sandy soil",
    "plant_type": "Tropical indoor",
    "location": "Kitchen",
    "last_fertilization": "2025-04-25"
  },
  {
    "name": "lurkrxvdel",
    "common_name": "Bamboo Palm",
    "scientific_name": "Chamaedorea seifrizii",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-18",
    "watering_frequency_days": 8,
    "soil_type": "Loamy soil",
    "plant_type": "Tropical indoor",
    "location": "Music Room",
    "last_fertilization": "2025-04-20"
  },
  {
    "name": "ioxgvwxifai",
    "common_name": "Aloe Vera",
    "scientific_name": "Aloe barbadensis miller",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-17",
    "watering_frequency_days": 10,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Flowering indoor",
    "location": "Upstairs",
    "last_fertilization": "2025-04-29"
  },
  {
    "name": "quajgehzyk",
    "common_name": "Succulent Mix",
    "scientific_name": "Various species",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-25",
    "watering_frequency_days": 4,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Flowering indoor",
    "location": "Kitchen",
    "last_fertilization": "2025-04-13"
  },
  {
    "name": "zud",
    "common_name": "Jade Plant",
    "scientific_name": "Crassula ovata",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-22",
    "watering_frequency_days": 11,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Air-purifying",
    "location": "Kitchen",
    "last_fertilization": "2025-03-21"
  },
  {
    "name": "wsbxvgmp",
    "common_name": "Philodendron",
    "scientific_name": "Philodendron hederaceum",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-27",
    "watering_frequency_days": 14,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Air-purifying",
    "location": " Downstairs Bedroom",
    "last_fertilization": "2025-03-25"
  },
  {
    "name": "udsjujiwgfjuv",
    "common_name": "Jade Plant",
    "scientific_name": "Crassula ovata",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-17",
    "watering_frequency_days": 11,
    "soil_type": "Sandy soil",
    "plant_type": "Desert succulent",
    "location": "Upstairs",
    "last_fertilization": "2025-03-19"
  },
  {
    "name": "hcakvvjvtjvp",
    "common_name": "Aloe Vera",
    "scientific_name": "Aloe barbadensis miller",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-23",
    "watering_frequency_days": 11,
    "soil_type": "Cactus mix",
    "plant_type": "Foliage plant",
    "location": "Upstairs Bedroom",
    "last_fertilization": "2025-04-06"
  },
  {
    "name": "zmm",
    "common_name": "Aloe Vera",
    "scientific_name": "Aloe barbadensis miller",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-17",
    "watering_frequency_days": 4,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Desert succulent",
    "location": "Upstairs Bedroom",
    "last_fertilization": "2025-04-25"
  },
  {
    "name": "oj",
    "common_name": "Rubber Plant",
    "scientific_name": "Ficus elastica",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-17",
    "watering_frequency_days": 6,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Air-purifying",
    "location": "Upstairs Bedroom",
    "last_fertilization": "2025-03-06"
  },
  {
    "name": "si",
    "common_name": "Snake Plant",
    "scientific_name": "Sansevieria trifasciata",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-23",
    "watering_frequency_days": 11,
    "soil_type": "Loamy soil",
    "plant_type": "Flowering indoor",
    "location": "Living Room",
    "last_fertilization": "2025-04-12"
  },
  {
    "name": "joeqvzrs",
    "common_name": "Areca Palm",
    "scientific_name": "Dypsis lutescens",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-26",
    "watering_frequency_days": 7,
    "soil_type": "Sandy soil",
    "plant_type": "Foliage plant",
    "location": "Upstairs",
    "last_fertilization": "2025-03-23"
  },
  {
    "name": "kycxjcerjmos",
    "common_name": "Calathea",
    "scientific_name": "Calathea orbifolia",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-22",
    "watering_frequency_days": 14,
    "soil_type": "Cactus mix",
    "plant_type": "Foliage plant",
    "location": "Bathroom",
    "last_fertilization": "2025-04-23"
  },
  {
    "name": "wvxesj",
    "common_name": "Cactus",
    "scientific_name": "Cactaceae family",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-15",
    "watering_frequency_days": 5,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Foliage plant",
    "location": "Bathroom",
    "last_fertilization": "2025-04-12"
  },
  {
    "name": "qqixqdnx",
    "common_name": "Philodendron",
    "scientific_name": "Philodendron hederaceum",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-29",
    "watering_frequency_days": 7,
    "soil_type": "Cactus mix",
    "plant_type": "Foliage plant",
    "location": "Music Room",
    "last_fertilization": "2025-03-11"
  },
  {
    "name": "rjiwgxyobnv",
    "common_name": "Boston Fern",
    "scientific_name": "Nephrolepis exaltata",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-21",
    "watering_frequency_days": 3,
    "soil_type": "Loamy soil",
    "plant_type": "Tropical indoor",
    "location": "Music Room",
    "last_fertilization": "2025-04-12"
  },
  {
    "name": "cliwvfrkhi",
    "common_name": "Bird of Paradise",
    "scientific_name": "Strelitzia reginae",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-27",
    "watering_frequency_days": 5,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Flowering indoor",
    "location": "Bathroom",
    "last_fertilization": "2025-04-07"
  },
  {
    "name": "d",
    "common_name": "Bird of Paradise",
    "scientific_name": "Strelitzia reginae",
    "description": "Purifies air and adds greenery to your space.",
    "last_water_date": "2025-04-19",
    "watering_frequency_days": 10,
    "soil_type": "Loamy soil",
    "plant_type": "Desert succulent",
    "location": "Bathroom",
    "last_fertilization": "2025-04-21"
  },
  {
    "name": "ummtgrfmayl",
    "common_name": "Philodendron",
    "scientific_name": "Philodendron hederaceum",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-26",
    "watering_frequency_days": 6,
    "soil_type": "Loamy soil",
    "plant_type": "Air-purifying",
    "location": "Kitchen",
    "last_fertilization": "2025-03-24"
  },
  {
    "name": "roox",
    "common_name": "Spider Plant",
    "scientific_name": "Chlorophytum comosum",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-21",
    "watering_frequency_days": 12,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Foliage plant",
    "location": "Music Room",
    "last_fertilization": "2025-04-08"
  },
  {
    "name": "fjyuyiemjmeiu",
    "common_name": "Areca Palm",
    "scientific_name": "Dypsis lutescens",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-23",
    "watering_frequency_days": 14,
    "soil_type": "Sandy soil",
    "plant_type": "Tropical indoor",
    "location": "Kitchen",
    "last_fertilization": "2025-04-27"
  },
  {
    "name": "qjfehdnicn",
    "common_name": "Pothos",
    "scientific_name": "Epipremnum aureum",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-18",
    "watering_frequency_days": 6,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Foliage plant",
    "location": "Office",
    "last_fertilization": "2025-03-12"
  },
  {
    "name": "zbpr",
    "common_name": "Fiddle Leaf Fig",
    "scientific_name": "Ficus lyrata",
    "description": "Purifies air and adds greenery to your space.",
    "last_water_date": "2025-04-16",
    "watering_frequency_days": 7,
    "soil_type": "Cactus mix",
    "plant_type": "Desert succulent",
    "location": "Kitchen",
    "last_fertilization": "2025-04-27"
  },
  {
    "name": "uy",
    "common_name": "Fiddle Leaf Fig",
    "scientific_name": "Ficus lyrata",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-28",
    "watering_frequency_days": 8,
    "soil_type": "Loamy soil",
    "plant_type": "Flowering indoor",
    "location": "Music Room",
    "last_fertilization": "2025-04-11"
  },
  {
    "name": "hsyincazkiasr",
    "common_name": "Snake Plant",
    "scientific_name": "Sansevieria trifasciata",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-19",
    "watering_frequency_days": 14,
    "soil_type": "Cactus mix",
    "plant_type": "Flowering indoor",
    "location": "Upstairs",
    "last_fertilization": "2025-04-23"
  },
  {
    "name": "nuudm",
    "common_name": "Cactus",
    "scientific_name": "Cactaceae family",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-16",
    "watering_frequency_days": 11,
    "soil_type": "Loamy soil",
    "plant_type": "Desert succulent",
    "location": "Upstairs",
    "last_fertilization": "2025-03-05"
  },
  {
    "name": "dbrczvalrgwag",
    "common_name": "Fiddle Leaf Fig",
    "scientific_name": "Ficus lyrata",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-16",
    "watering_frequency_days": 13,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Air-purifying",
    "location": "Living Room",
    "last_fertilization": "2025-04-17"
  },
  {
    "name": "ytuirjhatbq",
    "common_name": "Jade Plant",
    "scientific_name": "Crassula ovata",
    "description": "Purifies air and adds greenery to your space.",
    "last_water_date": "2025-04-28",
    "watering_frequency_days": 6,
    "soil_type": "Sandy soil",
    "plant_type": "Tropical indoor",
    "location": " Downstairs Bedroom",
    "last_fertilization": "2025-03-25"
  },
  {
    "name": "iuuppwbqtia",
    "common_name": "ZZ Plant",
    "scientific_name": "Zamioculcas zamiifolia",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-22",
    "watering_frequency_days": 4,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Flowering indoor",
    "location": " Downstairs Bedroom",
    "last_fertilization": "2025-03-04"
  },
  {
    "name": "dylawzbqjim",
    "common_name": "Dracaena",
    "scientific_name": "Dracaena marginata",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-17",
    "watering_frequency_days": 5,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Tropical indoor",
    "location": "Music Room",
    "last_fertilization": "2025-03-20"
  },
  {
    "name": "ebuzwb",
    "common_name": "Philodendron",
    "scientific_name": "Philodendron hederaceum",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-17",
    "watering_frequency_days": 10,
    "soil_type": "Sandy soil",
    "plant_type": "Flowering indoor",
    "location": "Upstairs",
    "last_fertilization": "2025-03-04"
  },
  {
    "name": "trvcyjnlp",
    "common_name": "Bamboo Palm",
    "scientific_name": "Chamaedorea seifrizii",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-22",
    "watering_frequency_days": 11,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Air-purifying",
    "location": "Office",
    "last_fertilization": "2025-04-04"
  },
  {
    "name": "yod",
    "common_name": "Bird of Paradise",
    "scientific_name": "Strelitzia reginae",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-23",
    "watering_frequency_days": 13,
    "soil_type": "Cactus mix",
    "plant_type": "Foliage plant",
    "location": "Bathroom",
    "last_fertilization": "2025-04-07"
  },
  {
    "name": "jtzchxdf",
    "common_name": "Fiddle Leaf Fig",
    "scientific_name": "Ficus lyrata",
    "description": "Purifies air and adds greenery to your space.",
    "last_water_date": "2025-04-15",
    "watering_frequency_days": 10,
    "soil_type": "Sandy soil",
    "plant_type": "Tropical indoor",
    "location": "Music Room",
    "last_fertilization": "2025-03-19"
  },
  {
    "name": "kxgnygkdmgbyb",
    "common_name": "Peace Lily",
    "scientific_name": "Spathiphyllum wallisii",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-18",
    "watering_frequency_days": 11,
    "soil_type": "Sandy soil",
    "plant_type": "Air-purifying",
    "location": "Music Room",
    "last_fertilization": "2025-04-04"
  },
  {
    "name": "ujhwzmx",
    "common_name": "Peace Lily",
    "scientific_name": "Spathiphyllum wallisii",
    "description": "Purifies air and adds greenery to your space.",
    "last_water_date": "2025-04-21",
    "watering_frequency_days": 12,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Tropical indoor",
    "location": "Office",
    "last_fertilization": "2025-04-08"
  },
  {
    "name": "lflzzsmmopwbr",
    "common_name": "Jade Plant",
    "scientific_name": "Crassula ovata",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-17",
    "watering_frequency_days": 9,
    "soil_type": "Sandy soil",
    "plant_type": "Desert succulent",
    "location": "Music Room",
    "last_fertilization": "2025-03-30"
  },
  {
    "name": "dpgqy",
    "common_name": "Philodendron",
    "scientific_name": "Philodendron hederaceum",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-29",
    "watering_frequency_days": 6,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Foliage plant",
    "location": "Upstairs",
    "last_fertilization": "2025-03-01"
  },
  {
    "name": "cx",
    "common_name": "Bird of Paradise",
    "scientific_name": "Strelitzia reginae",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-26",
    "watering_frequency_days": 4,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Flowering indoor",
    "location": "Kitchen",
    "last_fertilization": "2025-04-18"
  },
  {
    "name": "iowpjuhw",
    "common_name": "Dracaena",
    "scientific_name": "Dracaena marginata",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-22",
    "watering_frequency_days": 10,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Flowering indoor",
    "location": "Upstairs Bedroom",
    "last_fertilization": "2025-03-22"
  },
  {
    "name": "ilkyowmv",
    "common_name": "Croton",
    "scientific_name": "Codiaeum variegatum",
    "description": "Purifies air and adds greenery to your space.",
    "last_water_date": "2025-04-22",
    "watering_frequency_days": 13,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Air-purifying",
    "location": "Music Room",
    "last_fertilization": "2025-03-21"
  },
  {
    "name": "osf",
    "common_name": "Dracaena",
    "scientific_name": "Dracaena marginata",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-21",
    "watering_frequency_days": 5,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Tropical indoor",
    "location": "Living Room",
    "last_fertilization": "2025-03-05"
  },
  {
    "name": "vne",
    "common_name": "Spider Plant",
    "scientific_name": "Chlorophytum comosum",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-25",
    "watering_frequency_days": 13,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Tropical indoor",
    "location": "Upstairs",
    "last_fertilization": "2025-03-07"
  },
  {
    "name": "fewyetcbl",
    "common_name": "Cactus",
    "scientific_name": "Cactaceae family",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-28",
    "watering_frequency_days": 11,
    "soil_type": "Loamy soil",
    "plant_type": "Desert succulent",
    "location": "Bathroom",
    "last_fertilization": "2025-03-31"
  },
  {
    "name": "vogi",
    "common_name": "Aloe Vera",
    "scientific_name": "Aloe barbadensis miller",
    "description": "Purifies air and adds greenery to your space.",
    "last_water_date": "2025-04-25",
    "watering_frequency_days": 6,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Air-purifying",
    "location": " Downstairs Bedroom",
    "last_fertilization": "2025-04-13"
  },
  {
    "name": "pmljefqwhxj",
    "common_name": "Fiddle Leaf Fig",
    "scientific_name": "Ficus lyrata",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-16",
    "watering_frequency_days": 8,
    "soil_type": "Sandy soil",
    "plant_type": "Flowering indoor",
    "location": "Music Room",
    "last_fertilization": "2025-03-14"
  },
  {
    "name": "sfoixh",
    "common_name": "Rubber Plant",
    "scientific_name": "Ficus elastica",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-18",
    "watering_frequency_days": 12,
    "soil_type": "Loamy soil",
    "plant_type": "Desert succulent",
    "location": "Music Room",
    "last_fertilization": "2025-03-25"
  },
  {
    "name": "nruoatlrsntc",
    "common_name": "Boston Fern",
    "scientific_name": "Nephrolepis exaltata",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-25",
    "watering_frequency_days": 13,
    "soil_type": "Loamy soil",
    "plant_type": "Flowering indoor",
    "location": "Office",
    "last_fertilization": "2025-04-26"
  },
  {
    "name": "phkgaiyd",
    "common_name": "Bamboo Palm",
    "scientific_name": "Chamaedorea seifrizii",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-20",
    "watering_frequency_days": 8,
    "soil_type": "Cactus mix",
    "plant_type": "Foliage plant",
    "location": "Upstairs Bedroom",
    "last_fertilization": "2025-04-13"
  },
  {
    "name": "bpgtgk",
    "common_name": "Cactus",
    "scientific_name": "Cactaceae family",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-20",
    "watering_frequency_days": 12,
    "soil_type": "Loamy soil",
    "plant_type": "Tropical indoor",
    "location": "Upstairs",
    "last_fertilization": "2025-04-11"
  },
  {
    "name": "ynhskboft",
    "common_name": "Cactus",
    "scientific_name": "Cactaceae family",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-23",
    "watering_frequency_days": 5,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Flowering indoor",
    "location": "Music Room",
    "last_fertilization": "2025-04-23"
  },
  {
    "name": "qkmgrqo",
    "common_name": "Pothos",
    "scientific_name": "Epipremnum aureum",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-24",
    "watering_frequency_days": 8,
    "soil_type": "Sandy soil",
    "plant_type": "Air-purifying",
    "location": "Office",
    "last_fertilization": "2025-03-08"
  },
  {
    "name": "zqxkwkvcjzhq",
    "common_name": "Areca Palm",
    "scientific_name": "Dypsis lutescens",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-24",
    "watering_frequency_days": 14,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Air-purifying",
    "location": "Office",
    "last_fertilization": "2025-03-24"
  },
  {
    "name": "lwahxlhaij",
    "common_name": "Dracaena",
    "scientific_name": "Dracaena marginata",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-22",
    "watering_frequency_days": 9,
    "soil_type": "Loamy soil",
    "plant_type": "Foliage plant",
    "location": "Music Room",
    "last_fertilization": "2025-03-01"
  },
  {
    "name": "pzftml",
    "common_name": "Dracaena",
    "scientific_name": "Dracaena marginata",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-22",
    "watering_frequency_days": 7,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Foliage plant",
    "location": "Music Room",
    "last_fertilization": "2025-04-10"
  },
  {
    "name": "epxsspbv",
    "common_name": "Croton",
    "scientific_name": "Codiaeum variegatum",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-28",
    "watering_frequency_days": 6,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Tropical indoor",
    "location": "Upstairs",
    "last_fertilization": "2025-04-26"
  },
  {
    "name": "cjaftnwmsgja",
    "common_name": "Croton",
    "scientific_name": "Codiaeum variegatum",
    "description": "Purifies air and adds greenery to your space.",
    "last_water_date": "2025-04-18",
    "watering_frequency_days": 7,
    "soil_type": "Loamy soil",
    "plant_type": "Tropical indoor",
    "location": "Upstairs",
    "last_fertilization": "2025-03-27"
  },
  {
    "name": "jsazmklp",
    "common_name": "Rubber Plant",
    "scientific_name": "Ficus elastica",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-18",
    "watering_frequency_days": 7,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Flowering indoor",
    "location": "Living Room",
    "last_fertilization": "2025-04-26"
  },
  {
    "name": "fsittmmfea",
    "common_name": "Rubber Plant",
    "scientific_name": "Ficus elastica",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-15",
    "watering_frequency_days": 10,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Air-purifying",
    "location": "Upstairs Bedroom",
    "last_fertilization": "2025-03-31"
  },
  {
    "name": "nvvclabzsxixm",
    "common_name": "Cactus",
    "scientific_name": "Cactaceae family",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-27",
    "watering_frequency_days": 7,
    "soil_type": "Cactus mix",
    "plant_type": "Air-purifying",
    "location": "Kitchen",
    "last_fertilization": "2025-03-13"
  },
  {
    "name": "tlpdx",
    "common_name": "Jade Plant",
    "scientific_name": "Crassula ovata",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-15",
    "watering_frequency_days": 6,
    "soil_type": "Loamy soil",
    "plant_type": "Tropical indoor",
    "location": "Kitchen",
    "last_fertilization": "2025-03-31"
  },
  {
    "name": "n",
    "common_name": "Rubber Plant",
    "scientific_name": "Ficus elastica",
    "description": "Purifies air and adds greenery to your space.",
    "last_water_date": "2025-04-18",
    "watering_frequency_days": 14,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Air-purifying",
    "location": " Downstairs Bedroom",
    "last_fertilization": "2025-04-19"
  },
  {
    "name": "cfx",
    "common_name": "Succulent Mix",
    "scientific_name": "Various species",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-17",
    "watering_frequency_days": 11,
    "soil_type": "Cactus mix",
    "plant_type": "Foliage plant",
    "location": " Downstairs Bedroom",
    "last_fertilization": "2025-03-08"
  },
  {
    "name": "poeimqxulyqyf",
    "common_name": "Areca Palm",
    "scientific_name": "Dypsis lutescens",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-29",
    "watering_frequency_days": 4,
    "soil_type": "Sandy soil",
    "plant_type": "Foliage plant",
    "location": "Office",
    "last_fertilization": "2025-04-18"
  },
  {
    "name": "ooncly",
    "common_name": "Rubber Plant",
    "scientific_name": "Ficus elastica",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-26",
    "watering_frequency_days": 9,
    "soil_type": "Cactus mix",
    "plant_type": "Foliage plant",
    "location": "Music Room",
    "last_fertilization": "2025-03-15"
  },
  {
    "name": "xwbheyc",
    "common_name": "Pothos",
    "scientific_name": "Epipremnum aureum",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-18",
    "watering_frequency_days": 3,
    "soil_type": "Loamy soil",
    "plant_type": "Flowering indoor",
    "location": "Music Room",
    "last_fertilization": "2025-03-14"
  },
  {
    "name": "tzpp",
    "common_name": "Croton",
    "scientific_name": "Codiaeum variegatum",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-29",
    "watering_frequency_days": 13,
    "soil_type": "Sandy soil",
    "plant_type": "Tropical indoor",
    "location": "Bathroom",
    "last_fertilization": "2025-03-29"
  },
  {
    "name": "ucyl",
    "common_name": "Rubber Plant",
    "scientific_name": "Ficus elastica",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-19",
    "watering_frequency_days": 11,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Air-purifying",
    "location": "Office",
    "last_fertilization": "2025-02-28"
  },
  {
    "name": "jzyiydoe",
    "common_name": "Bamboo Palm",
    "scientific_name": "Chamaedorea seifrizii",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-22",
    "watering_frequency_days": 6,
    "soil_type": "Sandy soil",
    "plant_type": "Flowering indoor",
    "location": "Living Room",
    "last_fertilization": "2025-03-29"
  },
  {
    "name": "clfd",
    "common_name": "Cactus",
    "scientific_name": "Cactaceae family",
    "description": "A beautiful and easy-to-care-for houseplant.",
    "last_water_date": "2025-04-22",
    "watering_frequency_days": 11,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Flowering indoor",
    "location": "Office",
    "last_fertilization": "2025-03-15"
  },
  {
    "name": "y",
    "common_name": "Monstera Deliciosa",
    "scientific_name": "Monstera deliciosa",
    "description": "Purifies air and adds greenery to your space.",
    "last_water_date": "2025-04-28",
    "watering_frequency_days": 11,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Desert succulent",
    "location": "Living Room",
    "last_fertilization": "2025-03-26"
  },
  {
    "name": "phadh",
    "common_name": "Cactus",
    "scientific_name": "Cactaceae family",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-27",
    "watering_frequency_days": 13,
    "soil_type": "Cactus mix",
    "plant_type": "Flowering indoor",
    "location": "Bathroom",
    "last_fertilization": "2025-04-04"
  },
  {
    "name": "gshnnx",
    "common_name": "Fiddle Leaf Fig",
    "scientific_name": "Ficus lyrata",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-17",
    "watering_frequency_days": 11,
    "soil_type": "Loamy soil",
    "plant_type": "Flowering indoor",
    "location": "Living Room",
    "last_fertilization": "2025-02-28"
  },
  {
    "name": "hybh",
    "common_name": "Pothos",
    "scientific_name": "Epipremnum aureum",
    "description": "Purifies air and adds greenery to your space.",
    "last_water_date": "2025-04-27",
    "watering_frequency_days": 3,
    "soil_type": "Cactus mix",
    "plant_type": "Flowering indoor",
    "location": "Living Room",
    "last_fertilization": "2025-03-24"
  },
  {
    "name": "tuqlsqcsz",
    "common_name": "Bamboo Palm",
    "scientific_name": "Chamaedorea seifrizii",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-16",
    "watering_frequency_days": 14,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Desert succulent",
    "location": "Upstairs",
    "last_fertilization": "2025-04-22"
  },
  {
    "name": "jjqjigmclvjb",
    "common_name": "Monstera Deliciosa",
    "scientific_name": "Monstera deliciosa",
    "description": "Known for its striking foliage and unique pattern.",
    "last_water_date": "2025-04-21",
    "watering_frequency_days": 9,
    "soil_type": "Cactus mix",
    "plant_type": "Desert succulent",
    "location": "Bathroom",
    "last_fertilization": "2025-03-13"
  },
  {
    "name": "wgwuzobt",
    "common_name": "Areca Palm",
    "scientific_name": "Dypsis lutescens",
    "description": "Low-maintenance and great for beginners.",
    "last_water_date": "2025-04-18",
    "watering_frequency_days": 9,
    "soil_type": "Well-draining peat-based mix",
    "plant_type": "Air-purifying",
    "location": "Office",
    "last_fertilization": "2025-03-23"
  },
  {
    "name": "cxek",
    "common_name": "Dracaena",
    "scientific_name": "Dracaena marginata",
    "description": "Purifies air and adds greenery to your space.",
    "last_water_date": "2025-04-17",
    "watering_frequency_days": 9,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Foliage plant",
    "location": "Music Room",
    "last_fertilization": "2025-04-24"
  },
  {
    "name": "ntwszlycz",
    "common_name": "Calathea",
    "scientific_name": "Calathea orbifolia",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-29",
    "watering_frequency_days": 4,
    "soil_type": "Cactus mix",
    "plant_type": "Flowering indoor",
    "location": "Upstairs",
    "last_fertilization": "2025-03-08"
  },
  {
    "name": "qrcpess",
    "common_name": "Bamboo Palm",
    "scientific_name": "Chamaedorea seifrizii",
    "description": "Thrives in bright, indirect light and adds a tropical feel.",
    "last_water_date": "2025-04-15",
    "watering_frequency_days": 5,
    "soil_type": "Moisture-retentive potting mix",
    "plant_type": "Air-purifying",
    "location": "Music Room",
    "last_fertilization": "2025-04-28"
  }
];
export const plants = mockPlants.map(plant => new Plant(plant));