export const mockPlants = [
    {
      "name": "Fiddle Leaf Fig",
      "scientific_name": "Ficus lyrata",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-24",
      "watering_frequency_days": 8,
      "soil_type": "Loamy soil",
      "plant_type": "Foliage plant",
      "location": "Bathroom",
      "last_fertilization": "2025-04-06"
    },
    {
      "name": "Snake Plant",
      "scientific_name": "Sansevieria trifasciata",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-19",
      "watering_frequency_days": 12,
      "soil_type": "Sandy soil",
      "plant_type": "Flowering indoor",
      "location": "Music Room",
      "last_fertilization": "2025-04-21"
    },
    {
      "name": "Pothos",
      "scientific_name": "Epipremnum aureum",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-14",
      "watering_frequency_days": 14,
      "soil_type": "Loamy soil",
      "plant_type": "Tropical indoor",
      "location": "Upstairs Bedroom",
      "last_fertilization": "2025-03-11"
    },
    {
      "name": "Philodendron",
      "scientific_name": "Philodendron hederaceum",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-26",
      "watering_frequency_days": 8,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Flowering indoor",
      "location": "Living Room",
      "last_fertilization": "2025-03-11"
    },
    {
      "name": "Monstera Deliciosa",
      "scientific_name": "Monstera deliciosa",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-17",
      "watering_frequency_days": 13,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Flowering indoor",
      "location": "Upstairs",
      "last_fertilization": "2025-03-14"
    },
    {
      "name": "Fiddle Leaf Fig",
      "scientific_name": "Ficus lyrata",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-28",
      "watering_frequency_days": 11,
      "soil_type": "Loamy soil",
      "plant_type": "Tropical indoor",
      "location": "Upstairs Bedroom",
      "last_fertilization": "2025-04-12"
    },
    {
      "name": "Croton",
      "scientific_name": "Codiaeum variegatum",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-16",
      "watering_frequency_days": 14,
      "soil_type": "Cactus mix",
      "plant_type": "Tropical indoor",
      "location": "Living Room",
      "last_fertilization": "2025-03-08"
    },
    {
      "name": "ZZ Plant",
      "scientific_name": "Zamioculcas zamiifolia",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-17",
      "watering_frequency_days": 8,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Foliage plant",
      "location": "Music Room",
      "last_fertilization": "2025-04-19"
    },
    {
      "name": "Aloe Vera",
      "scientific_name": "Aloe barbadensis miller",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-15",
      "watering_frequency_days": 12,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Foliage plant",
      "location": "Upstairs",
      "last_fertilization": "2025-04-13"
    },
    {
      "name": "Jade Plant",
      "scientific_name": "Crassula ovata",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-20",
      "watering_frequency_days": 11,
      "soil_type": "Cactus mix",
      "plant_type": "Foliage plant",
      "location": "Living Room",
      "last_fertilization": "2025-04-12"
    },
    {
      "name": "Croton",
      "scientific_name": "Codiaeum variegatum",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-28",
      "watering_frequency_days": 9,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Air-purifying",
      "location": "Upstairs Bedroom",
      "last_fertilization": "2025-02-28"
    },
    {
      "name": "Bamboo Palm",
      "scientific_name": "Chamaedorea seifrizii",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-15",
      "watering_frequency_days": 14,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Foliage plant",
      "location": " Downstairs Bedroom",
      "last_fertilization": "2025-03-12"
    },
    {
      "name": "Bird of Paradise",
      "scientific_name": "Strelitzia reginae",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-14",
      "watering_frequency_days": 9,
      "soil_type": "Loamy soil",
      "plant_type": "Flowering indoor",
      "location": "Music Room",
      "last_fertilization": "2025-03-07"
    },
    {
      "name": "Monstera Deliciosa",
      "scientific_name": "Monstera deliciosa",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-27",
      "watering_frequency_days": 4,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Tropical indoor",
      "location": "Upstairs",
      "last_fertilization": "2025-04-12"
    },
    {
      "name": "Jade Plant",
      "scientific_name": "Crassula ovata",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-21",
      "watering_frequency_days": 4,
      "soil_type": "Cactus mix",
      "plant_type": "Desert succulent",
      "location": "Upstairs Bedroom",
      "last_fertilization": "2025-04-08"
    },
    {
      "name": "Monstera Deliciosa",
      "scientific_name": "Monstera deliciosa",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-22",
      "watering_frequency_days": 11,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Tropical indoor",
      "location": "Living Room",
      "last_fertilization": "2025-02-27"
    },
    {
      "name": "Bamboo Palm",
      "scientific_name": "Chamaedorea seifrizii",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-18",
      "watering_frequency_days": 3,
      "soil_type": "Sandy soil",
      "plant_type": "Flowering indoor",
      "location": "Office",
      "last_fertilization": "2025-04-23"
    },
    {
      "name": "Monstera Deliciosa",
      "scientific_name": "Monstera deliciosa",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-18",
      "watering_frequency_days": 8,
      "soil_type": "Loamy soil",
      "plant_type": "Tropical indoor",
      "location": "Bathroom",
      "last_fertilization": "2025-03-21"
    },
    {
      "name": "Dracaena",
      "scientific_name": "Dracaena marginata",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-15",
      "watering_frequency_days": 7,
      "soil_type": "Loamy soil",
      "plant_type": "Desert succulent",
      "location": "Music Room",
      "last_fertilization": "2025-04-16"
    },
    {
      "name": "ZZ Plant",
      "scientific_name": "Zamioculcas zamiifolia",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-21",
      "watering_frequency_days": 4,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Foliage plant",
      "location": "Upstairs",
      "last_fertilization": "2025-03-27"
    },
    {
      "name": "Fiddle Leaf Fig",
      "scientific_name": "Ficus lyrata",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-16",
      "watering_frequency_days": 12,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Desert succulent",
      "location": "Office",
      "last_fertilization": "2025-04-02"
    },
    {
      "name": "Philodendron",
      "scientific_name": "Philodendron hederaceum",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-16",
      "watering_frequency_days": 7,
      "soil_type": "Sandy soil",
      "plant_type": "Flowering indoor",
      "location": "Kitchen",
      "last_fertilization": "2025-03-18"
    },
    {
      "name": "Pothos",
      "scientific_name": "Epipremnum aureum",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-16",
      "watering_frequency_days": 12,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Flowering indoor",
      "location": "Upstairs Bedroom",
      "last_fertilization": "2025-03-20"
    },
    {
      "name": "Jade Plant",
      "scientific_name": "Crassula ovata",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-22",
      "watering_frequency_days": 4,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Desert succulent",
      "location": "Music Room",
      "last_fertilization": "2025-03-12"
    },
    {
      "name": "Cactus",
      "scientific_name": "Cactaceae family",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-22",
      "watering_frequency_days": 6,
      "soil_type": "Cactus mix",
      "plant_type": "Desert succulent",
      "location": "Bathroom",
      "last_fertilization": "2025-03-01"
    },
    {
      "name": "Aloe Vera",
      "scientific_name": "Aloe barbadensis miller",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-16",
      "watering_frequency_days": 3,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Foliage plant",
      "location": " Downstairs Bedroom",
      "last_fertilization": "2025-04-26"
    },
    {
      "name": "Dracaena",
      "scientific_name": "Dracaena marginata",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-27",
      "watering_frequency_days": 8,
      "soil_type": "Loamy soil",
      "plant_type": "Flowering indoor",
      "location": "Upstairs Bedroom",
      "last_fertilization": "2025-03-11"
    },
    {
      "name": "Fiddle Leaf Fig",
      "scientific_name": "Ficus lyrata",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-28",
      "watering_frequency_days": 14,
      "soil_type": "Cactus mix",
      "plant_type": "Desert succulent",
      "location": "Upstairs Bedroom",
      "last_fertilization": "2025-03-13"
    },
    {
      "name": "Cactus",
      "scientific_name": "Cactaceae family",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-16",
      "watering_frequency_days": 7,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Air-purifying",
      "location": "Upstairs",
      "last_fertilization": "2025-03-26"
    },
    {
      "name": "Aloe Vera",
      "scientific_name": "Aloe barbadensis miller",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-20",
      "watering_frequency_days": 3,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Foliage plant",
      "location": " Downstairs Bedroom",
      "last_fertilization": "2025-03-24"
    },
    {
      "name": "Areca Palm",
      "scientific_name": "Dypsis lutescens",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-19",
      "watering_frequency_days": 6,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Air-purifying",
      "location": "Kitchen",
      "last_fertilization": "2025-04-12"
    },
    {
      "name": "Philodendron",
      "scientific_name": "Philodendron hederaceum",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-23",
      "watering_frequency_days": 10,
      "soil_type": "Cactus mix",
      "plant_type": "Air-purifying",
      "location": "Music Room",
      "last_fertilization": "2025-04-12"
    },
    {
      "name": "Calathea",
      "scientific_name": "Calathea orbifolia",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-18",
      "watering_frequency_days": 8,
      "soil_type": "Cactus mix",
      "plant_type": "Air-purifying",
      "location": "Office",
      "last_fertilization": "2025-03-12"
    },
    {
      "name": "Bamboo Palm",
      "scientific_name": "Chamaedorea seifrizii",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-26",
      "watering_frequency_days": 4,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Foliage plant",
      "location": "Music Room",
      "last_fertilization": "2025-04-03"
    },
    {
      "name": "Bird of Paradise",
      "scientific_name": "Strelitzia reginae",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-25",
      "watering_frequency_days": 5,
      "soil_type": "Loamy soil",
      "plant_type": "Foliage plant",
      "location": "Living Room",
      "last_fertilization": "2025-03-14"
    },
    {
      "name": "Bird of Paradise",
      "scientific_name": "Strelitzia reginae",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-15",
      "watering_frequency_days": 13,
      "soil_type": "Sandy soil",
      "plant_type": "Foliage plant",
      "location": "Kitchen",
      "last_fertilization": "2025-03-28"
    },
    {
      "name": "Dracaena",
      "scientific_name": "Dracaena marginata",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-25",
      "watering_frequency_days": 3,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Foliage plant",
      "location": "Upstairs",
      "last_fertilization": "2025-04-06"
    },
    {
      "name": "Fiddle Leaf Fig",
      "scientific_name": "Ficus lyrata",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-28",
      "watering_frequency_days": 5,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Air-purifying",
      "location": " Downstairs Bedroom",
      "last_fertilization": "2025-03-20"
    },
    {
      "name": "Pothos",
      "scientific_name": "Epipremnum aureum",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-14",
      "watering_frequency_days": 14,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Foliage plant",
      "location": "Bathroom",
      "last_fertilization": "2025-04-17"
    },
    {
      "name": "ZZ Plant",
      "scientific_name": "Zamioculcas zamiifolia",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-20",
      "watering_frequency_days": 8,
      "soil_type": "Loamy soil",
      "plant_type": "Tropical indoor",
      "location": "Bathroom",
      "last_fertilization": "2025-04-27"
    },
    {
      "name": "Rubber Plant",
      "scientific_name": "Ficus elastica",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-20",
      "watering_frequency_days": 11,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Flowering indoor",
      "location": "Kitchen",
      "last_fertilization": "2025-04-09"
    },
    {
      "name": "Snake Plant",
      "scientific_name": "Sansevieria trifasciata",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-27",
      "watering_frequency_days": 10,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Flowering indoor",
      "location": "Music Room",
      "last_fertilization": "2025-04-25"
    },
    {
      "name": "Peace Lily",
      "scientific_name": "Spathiphyllum wallisii",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-19",
      "watering_frequency_days": 9,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Air-purifying",
      "location": "Kitchen",
      "last_fertilization": "2025-04-11"
    },
    {
      "name": "Calathea",
      "scientific_name": "Calathea orbifolia",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-15",
      "watering_frequency_days": 9,
      "soil_type": "Cactus mix",
      "plant_type": "Foliage plant",
      "location": "Office",
      "last_fertilization": "2025-04-03"
    },
    {
      "name": "Succulent Mix",
      "scientific_name": "Various species",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-17",
      "watering_frequency_days": 7,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Foliage plant",
      "location": "Upstairs",
      "last_fertilization": "2025-04-02"
    },
    {
      "name": "Jade Plant",
      "scientific_name": "Crassula ovata",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-24",
      "watering_frequency_days": 7,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Foliage plant",
      "location": "Upstairs",
      "last_fertilization": "2025-03-21"
    },
    {
      "name": "Rubber Plant",
      "scientific_name": "Ficus elastica",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-28",
      "watering_frequency_days": 6,
      "soil_type": "Cactus mix",
      "plant_type": "Flowering indoor",
      "location": "Upstairs",
      "last_fertilization": "2025-04-13"
    },
    {
      "name": "Cactus",
      "scientific_name": "Cactaceae family",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-16",
      "watering_frequency_days": 12,
      "soil_type": "Loamy soil",
      "plant_type": "Foliage plant",
      "location": "Kitchen",
      "last_fertilization": "2025-03-24"
    },
    {
      "name": "Bird of Paradise",
      "scientific_name": "Strelitzia reginae",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-14",
      "watering_frequency_days": 10,
      "soil_type": "Sandy soil",
      "plant_type": "Foliage plant",
      "location": " Downstairs Bedroom",
      "last_fertilization": "2025-04-27"
    },
    {
      "name": "ZZ Plant",
      "scientific_name": "Zamioculcas zamiifolia",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-23",
      "watering_frequency_days": 7,
      "soil_type": "Cactus mix",
      "plant_type": "Flowering indoor",
      "location": "Bathroom",
      "last_fertilization": "2025-04-06"
    },
    {
      "name": "Rubber Plant",
      "scientific_name": "Ficus elastica",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-23",
      "watering_frequency_days": 3,
      "soil_type": "Sandy soil",
      "plant_type": "Desert succulent",
      "location": "Bathroom",
      "last_fertilization": "2025-03-19"
    },
    {
      "name": "Croton",
      "scientific_name": "Codiaeum variegatum",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-25",
      "watering_frequency_days": 5,
      "soil_type": "Sandy soil",
      "plant_type": "Foliage plant",
      "location": "Upstairs",
      "last_fertilization": "2025-04-05"
    },
    {
      "name": "Areca Palm",
      "scientific_name": "Dypsis lutescens",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-18",
      "watering_frequency_days": 14,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Air-purifying",
      "location": "Upstairs",
      "last_fertilization": "2025-03-06"
    },
    {
      "name": "Aloe Vera",
      "scientific_name": "Aloe barbadensis miller",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-19",
      "watering_frequency_days": 14,
      "soil_type": "Cactus mix",
      "plant_type": "Flowering indoor",
      "location": " Downstairs Bedroom",
      "last_fertilization": "2025-03-02"
    },
    {
      "name": "Croton",
      "scientific_name": "Codiaeum variegatum",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-24",
      "watering_frequency_days": 14,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Tropical indoor",
      "location": "Upstairs Bedroom",
      "last_fertilization": "2025-03-16"
    },
    {
      "name": "Aloe Vera",
      "scientific_name": "Aloe barbadensis miller",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-24",
      "watering_frequency_days": 6,
      "soil_type": "Cactus mix",
      "plant_type": "Desert succulent",
      "location": "Upstairs Bedroom",
      "last_fertilization": "2025-04-08"
    },
    {
      "name": "Dracaena",
      "scientific_name": "Dracaena marginata",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-14",
      "watering_frequency_days": 5,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Desert succulent",
      "location": "Upstairs",
      "last_fertilization": "2025-03-25"
    },
    {
      "name": "ZZ Plant",
      "scientific_name": "Zamioculcas zamiifolia",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-17",
      "watering_frequency_days": 6,
      "soil_type": "Sandy soil",
      "plant_type": "Air-purifying",
      "location": "Upstairs",
      "last_fertilization": "2025-04-27"
    },
    {
      "name": "Fiddle Leaf Fig",
      "scientific_name": "Ficus lyrata",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-28",
      "watering_frequency_days": 10,
      "soil_type": "Cactus mix",
      "plant_type": "Flowering indoor",
      "location": "Upstairs Bedroom",
      "last_fertilization": "2025-04-03"
    },
    {
      "name": "Dracaena",
      "scientific_name": "Dracaena marginata",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-27",
      "watering_frequency_days": 5,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Flowering indoor",
      "location": "Office",
      "last_fertilization": "2025-03-07"
    },
    {
      "name": "Pothos",
      "scientific_name": "Epipremnum aureum",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-18",
      "watering_frequency_days": 6,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Desert succulent",
      "location": "Bathroom",
      "last_fertilization": "2025-04-18"
    },
    {
      "name": "Snake Plant",
      "scientific_name": "Sansevieria trifasciata",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-27",
      "watering_frequency_days": 12,
      "soil_type": "Cactus mix",
      "plant_type": "Flowering indoor",
      "location": "Living Room",
      "last_fertilization": "2025-04-11"
    },
    {
      "name": "Pothos",
      "scientific_name": "Epipremnum aureum",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-15",
      "watering_frequency_days": 8,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Tropical indoor",
      "location": "Upstairs",
      "last_fertilization": "2025-03-09"
    },
    {
      "name": "Fiddle Leaf Fig",
      "scientific_name": "Ficus lyrata",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-28",
      "watering_frequency_days": 5,
      "soil_type": "Loamy soil",
      "plant_type": "Foliage plant",
      "location": "Upstairs",
      "last_fertilization": "2025-03-03"
    },
    {
      "name": "Areca Palm",
      "scientific_name": "Dypsis lutescens",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-14",
      "watering_frequency_days": 3,
      "soil_type": "Sandy soil",
      "plant_type": "Foliage plant",
      "location": "Music Room",
      "last_fertilization": "2025-04-08"
    },
    {
      "name": "Bird of Paradise",
      "scientific_name": "Strelitzia reginae",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-17",
      "watering_frequency_days": 4,
      "soil_type": "Cactus mix",
      "plant_type": "Tropical indoor",
      "location": "Bathroom",
      "last_fertilization": "2025-04-24"
    },
    {
      "name": "Succulent Mix",
      "scientific_name": "Various species",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-15",
      "watering_frequency_days": 5,
      "soil_type": "Sandy soil",
      "plant_type": "Flowering indoor",
      "location": "Bathroom",
      "last_fertilization": "2025-04-06"
    },
    {
      "name": "Bird of Paradise",
      "scientific_name": "Strelitzia reginae",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-21",
      "watering_frequency_days": 10,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Air-purifying",
      "location": "Office",
      "last_fertilization": "2025-04-17"
    },
    {
      "name": "Philodendron",
      "scientific_name": "Philodendron hederaceum",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-28",
      "watering_frequency_days": 12,
      "soil_type": "Cactus mix",
      "plant_type": "Desert succulent",
      "location": "Upstairs",
      "last_fertilization": "2025-04-01"
    },
    {
      "name": "ZZ Plant",
      "scientific_name": "Zamioculcas zamiifolia",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-28",
      "watering_frequency_days": 11,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Foliage plant",
      "location": "Music Room",
      "last_fertilization": "2025-04-25"
    },
    {
      "name": "Succulent Mix",
      "scientific_name": "Various species",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-28",
      "watering_frequency_days": 14,
      "soil_type": "Sandy soil",
      "plant_type": "Tropical indoor",
      "location": "Kitchen",
      "last_fertilization": "2025-04-22"
    },
    {
      "name": "Fiddle Leaf Fig",
      "scientific_name": "Ficus lyrata",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-16",
      "watering_frequency_days": 6,
      "soil_type": "Sandy soil",
      "plant_type": "Air-purifying",
      "location": "Upstairs",
      "last_fertilization": "2025-03-10"
    },
    {
      "name": "Spider Plant",
      "scientific_name": "Chlorophytum comosum",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-16",
      "watering_frequency_days": 12,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Foliage plant",
      "location": "Kitchen",
      "last_fertilization": "2025-04-20"
    },
    {
      "name": "Philodendron",
      "scientific_name": "Philodendron hederaceum",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-18",
      "watering_frequency_days": 8,
      "soil_type": "Sandy soil",
      "plant_type": "Foliage plant",
      "location": " Downstairs Bedroom",
      "last_fertilization": "2025-04-25"
    },
    {
      "name": "Pothos",
      "scientific_name": "Epipremnum aureum",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-25",
      "watering_frequency_days": 4,
      "soil_type": "Sandy soil",
      "plant_type": "Desert succulent",
      "location": "Living Room",
      "last_fertilization": "2025-03-15"
    },
    {
      "name": "Succulent Mix",
      "scientific_name": "Various species",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-21",
      "watering_frequency_days": 10,
      "soil_type": "Sandy soil",
      "plant_type": "Flowering indoor",
      "location": "Office",
      "last_fertilization": "2025-04-21"
    },
    {
      "name": "Rubber Plant",
      "scientific_name": "Ficus elastica",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-16",
      "watering_frequency_days": 9,
      "soil_type": "Sandy soil",
      "plant_type": "Flowering indoor",
      "location": "Kitchen",
      "last_fertilization": "2025-04-13"
    },
    {
      "name": "Bird of Paradise",
      "scientific_name": "Strelitzia reginae",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-16",
      "watering_frequency_days": 9,
      "soil_type": "Sandy soil",
      "plant_type": "Tropical indoor",
      "location": "Upstairs",
      "last_fertilization": "2025-03-20"
    },
    {
      "name": "Dracaena",
      "scientific_name": "Dracaena marginata",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-24",
      "watering_frequency_days": 14,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Foliage plant",
      "location": " Downstairs Bedroom",
      "last_fertilization": "2025-03-03"
    },
    {
      "name": "Bamboo Palm",
      "scientific_name": "Chamaedorea seifrizii",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-17",
      "watering_frequency_days": 12,
      "soil_type": "Loamy soil",
      "plant_type": "Flowering indoor",
      "location": "Living Room",
      "last_fertilization": "2025-02-27"
    },
    {
      "name": "Bamboo Palm",
      "scientific_name": "Chamaedorea seifrizii",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-18",
      "watering_frequency_days": 6,
      "soil_type": "Loamy soil",
      "plant_type": "Air-purifying",
      "location": "Office",
      "last_fertilization": "2025-03-10"
    },
    {
      "name": "Aloe Vera",
      "scientific_name": "Aloe barbadensis miller",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-14",
      "watering_frequency_days": 8,
      "soil_type": "Loamy soil",
      "plant_type": "Foliage plant",
      "location": "Upstairs Bedroom",
      "last_fertilization": "2025-03-09"
    },
    {
      "name": "ZZ Plant",
      "scientific_name": "Zamioculcas zamiifolia",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-24",
      "watering_frequency_days": 3,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Air-purifying",
      "location": "Living Room",
      "last_fertilization": "2025-03-29"
    },
    {
      "name": "ZZ Plant",
      "scientific_name": "Zamioculcas zamiifolia",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-25",
      "watering_frequency_days": 13,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Flowering indoor",
      "location": "Music Room",
      "last_fertilization": "2025-03-03"
    },
    {
      "name": "Fiddle Leaf Fig",
      "scientific_name": "Ficus lyrata",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-25",
      "watering_frequency_days": 4,
      "soil_type": "Moisture-retentive potting mix",
      "plant_type": "Air-purifying",
      "location": "Upstairs Bedroom",
      "last_fertilization": "2025-04-23"
    },
    {
      "name": "Monstera Deliciosa",
      "scientific_name": "Monstera deliciosa",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-23",
      "watering_frequency_days": 7,
      "soil_type": "Sandy soil",
      "plant_type": "Air-purifying",
      "location": "Music Room",
      "last_fertilization": "2025-04-07"
    },
    {
      "name": "Monstera Deliciosa",
      "scientific_name": "Monstera deliciosa",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-15",
      "watering_frequency_days": 8,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Air-purifying",
      "location": "Living Room",
      "last_fertilization": "2025-03-30"
    },
    {
      "name": "Philodendron",
      "scientific_name": "Philodendron hederaceum",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-28",
      "watering_frequency_days": 4,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Tropical indoor",
      "location": " Downstairs Bedroom",
      "last_fertilization": "2025-04-26"
    },
    {
      "name": "Calathea",
      "scientific_name": "Calathea orbifolia",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-19",
      "watering_frequency_days": 8,
      "soil_type": "Loamy soil",
      "plant_type": "Air-purifying",
      "location": "Upstairs",
      "last_fertilization": "2025-03-02"
    },
    {
      "name": "Philodendron",
      "scientific_name": "Philodendron hederaceum",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-18",
      "watering_frequency_days": 12,
      "soil_type": "Loamy soil",
      "plant_type": "Desert succulent",
      "location": "Upstairs Bedroom",
      "last_fertilization": "2025-04-19"
    },
    {
      "name": "Bamboo Palm",
      "scientific_name": "Chamaedorea seifrizii",
      "description": "Low-maintenance and great for beginners.",
      "last_water_date": "2025-04-24",
      "watering_frequency_days": 12,
      "soil_type": "Cactus mix",
      "plant_type": "Desert succulent",
      "location": "Music Room",
      "last_fertilization": "2025-03-22"
    },
    {
      "name": "Croton",
      "scientific_name": "Codiaeum variegatum",
      "description": "Thrives in bright, indirect light and adds a tropical feel.",
      "last_water_date": "2025-04-16",
      "watering_frequency_days": 9,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Air-purifying",
      "location": "Music Room",
      "last_fertilization": "2025-03-02"
    },
    {
      "name": "Monstera Deliciosa",
      "scientific_name": "Monstera deliciosa",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-26",
      "watering_frequency_days": 3,
      "soil_type": "Cactus mix",
      "plant_type": "Desert succulent",
      "location": "Kitchen",
      "last_fertilization": "2025-04-20"
    },
    {
      "name": "Snake Plant",
      "scientific_name": "Sansevieria trifasciata",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-24",
      "watering_frequency_days": 3,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Air-purifying",
      "location": "Living Room",
      "last_fertilization": "2025-03-17"
    },
    {
      "name": "Snake Plant",
      "scientific_name": "Sansevieria trifasciata",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-24",
      "watering_frequency_days": 6,
      "soil_type": "Sandy soil",
      "plant_type": "Air-purifying",
      "location": "Upstairs Bedroom",
      "last_fertilization": "2025-03-29"
    },
    {
      "name": "Succulent Mix",
      "scientific_name": "Various species",
      "description": "Known for its striking foliage and unique pattern.",
      "last_water_date": "2025-04-18",
      "watering_frequency_days": 13,
      "soil_type": "Sandy soil",
      "plant_type": "Foliage plant",
      "location": " Downstairs Bedroom",
      "last_fertilization": "2025-04-01"
    },
    {
      "name": "ZZ Plant",
      "scientific_name": "Zamioculcas zamiifolia",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-28",
      "watering_frequency_days": 11,
      "soil_type": "Cactus mix",
      "plant_type": "Air-purifying",
      "location": "Upstairs",
      "last_fertilization": "2025-04-15"
    },
    {
      "name": "Areca Palm",
      "scientific_name": "Dypsis lutescens",
      "description": "Purifies air and adds greenery to your space.",
      "last_water_date": "2025-04-19",
      "watering_frequency_days": 10,
      "soil_type": "Well-draining peat-based mix",
      "plant_type": "Air-purifying",
      "location": " Downstairs Bedroom",
      "last_fertilization": "2025-03-03"
    },
    {
      "name": "Rubber Plant",
      "scientific_name": "Ficus elastica",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-23",
      "watering_frequency_days": 3,
      "soil_type": "Sandy soil",
      "plant_type": "Desert succulent",
      "location": "Kitchen",
      "last_fertilization": "2025-04-14"
    },
    {
      "name": "Bird of Paradise",
      "scientific_name": "Strelitzia reginae",
      "description": "A beautiful and easy-to-care-for houseplant.",
      "last_water_date": "2025-04-17",
      "watering_frequency_days": 12,
      "soil_type": "Cactus mix",
      "plant_type": "Air-purifying",
      "location": "Living Room",
      "last_fertilization": "2025-04-15"
    }
  ]